server:
  port: 12333

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: status
  mapper-locations: classpath:mapper/*.xml

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://121.196.148.150:3306/blog?serverTimezone=GMT%2B8&userUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Root123456
  devtools:
    restart:
      enabled: true # 开启热部署
      additional-paths: src/main/java/cn/christi #热部署包

swagger:
  enable: true